[theme]
base = "light"
primaryColor = "#0E9AA7"
backgroundColor = "#F4F7FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#344054"
font = "sans serif"
baseRadius = "0.7rem"
borderColor = "#E1E8EF"
showWidgetBorder = true

[server]
headless = true
port = 8501
enableStaticServing = true
maxUploadSize = 25

[browser]
gatherUsageStats = false
